### ISSUE TITLE
터치이벤트 처리가 궁금합니다.

### ISSUE THREAD

**Issue by cloudeyes** [jsdevkr/axui-datagrid#31]
안녕하세요? 좋은 컴포넌트를 오픈소스로 공개해주셔서 감사합니다.

태블릿에서 사용할 웹 페이지를 만들고 있는데
터치 이벤트 처리를 어떻게 해야 하는지 궁금합니다.

감사합니다.
김용기 드림.

**Comment by cloudeyes** [comment]
답변 감사합니다.
저도 포크해서 개인적으로 테스트해보겠습니다.

**Comment by thomasJang** [comment]
가속처리는 안되었지만 터치스크롤 기능은 구현 했습니다.
이벤트를 막는 일이 어렵군요.~

**Comment by cloudeyes** [comment]
방금 받아서 완료하신거 확인했습니다.  감사합니다. :-)

그리고 autoprefixer 에서 다음과 같은 경고를 주는데 수정 부탁드립니다.
```
Gradient has outdated direction syntax. New syntax is like `to left` in stead of `right`
```
`index.scss` 파일 273행에 `to` 가 빠진 부분이 있습니다.

다시한번 훌륭한 컴포넌트를 만들어주셔서 감사드립니다.
즐거운 하루 되세요.
