### ISSUE TITLE
기능에 관해서 질문드립니다.

### ISSUE THREAD

**Issue by mucsiza** [jsdevkr/axui-datagrid#59]
axisj 부터 잘 사용해오고 있는 개발자 입니다.

이번에 리엑트를 사용하면서 데이터그리드를 사용하게 되었습니다.

혹시나 지금 이 기능이 있는것인데 제가 못찾아서 사용하지 못하는건지..
아니면 아직 구현이 안되어 있는지 궁금해서 질문올립니다.

- row 별 css 클래스 적용 ( background color 를 변경하기 위한 )

수고하세요.

**Comment by thomasJang** [comment]
row별 클래스 적용은 기능 구현 전입니다.
기능 필요하신 것 있으면 의견 주세요.

틈틈히 추가 해보겠습니다.

**Comment by mucsiza** [comment]
나머지는 별 문제없이 잘 사용하고 있습니다.

추가적으로 Excel 관련된 함수도 있었으면 합니다.
-> 현재는 다른 라이브러리를 가져와 사용하고 있습니다.
