### ISSUE TITLE
align 에 관해서 질문드립니다.

### ISSUE THREAD

**Issue by mucsiza** [jsdevkr/axui-datagrid#61]
{key:"amount”, label:”금액”, width:90, align:"right", formatter: "money"},

위와 같이 column 에 align 을 주면 잘작동합니다.

하지만 

header option 에 align: ‘center’ 를 줘도 작동하지를 않습니다.

이 column 에 right 를 준탓인지 header 도 오른쪽으로 정렬되어있습니다.

컬럼에 align 값이 있으면 header의 align 값이 적용이 안되는것인지 궁금합니다.

수고하세요.

**Comment by thomasJang** [comment]
네. column의 align속성이 우선합니다.
